let
    pkgs = import ../nix/nixpkgs.nix {};

in (pkgs.emacsPackagesFor pkgs.emacs).emacsWithPackages (epkgs: (with epkgs; [
    # agda2-mode # broken on M1? 2022-05-07
    # pkgs.emacsPackages.proofgeneral_HEAD
  dash
  f
  s
    add-node-modules-path
    buffer-move
    capnp-mode
    clojure-mode
    coffee-mode
    color-identifiers-mode
    company
    company-c-headers
    counsel
    csv-mode
    dash-at-point
    default-text-scale
    diminish
    direnv
    dockerfile-mode
    dumb-jump
    eat
    edit-indirect
    editorconfig
    emmet-mode
    ess
    evil
    evil-collection
    exec-path-from-shell
    feature-mode
    fic-mode
    flycheck
    flycheck-haskell
    git-link
    go-mode
    groovy-mode
    haskell-mode
    highlight-escape-sequences
    highlight-indent-guides
    highlight-quoted
    idris-mode
    inf-ruby
    ivy
    just-mode
    kotlin-mode
    ledger-mode
    magit
    markdown-mode
    native-complete
    nginx-mode
    nix-mode
    nodejs-repl
    org-cliplink
    orgit
    outline-indent
    ox-jira
    pandoc-mode
    persp-projectile
    perspective
    poly-markdown
    polymode
    powerline
    prettier
    projectile
    protobuf-mode
    purescript-mode
    py-isort
    pyvenv
    racket-mode
    rainbow-delimiters
    rainbow-mode
    rbs-mode
    real-auto-save
    restclient
    rg
    rspec-mode
    rubocop
    ruby-test-mode
    rust-mode
    s
    sed-mode
    smartparens
    swift-mode
    systemd
    terraform-mode
    tide
    toml-mode
    treesit-grammars.with-all-grammars
    typescript-mode
    unfill
    use-package
    w3m
    web-mode
    window-number
    yaml-mode
    yasnippet
  ]
  ))
