let
    pkgs = import ../nix/nixpkgs.nix {};

in (pkgs.emacsPackagesFor pkgs.emacs30).emacsWithPackages (epkgs: (with epkgs; [
    # agda2-mode # broken on M1? 2022-05-07
    # pkgs.emacsPackages.proofgeneral_HEAD
    add-node-modules-path
    auto-compile
    buffer-move
    capnp-mode
    clojure-mode
    coffee-mode
    color-identifiers-mode
    company
    company-c-headers
    counsel
    counsel-dash
    csv-mode
    dash # list library
    dash-docs
    default-text-scale
    diminish
    direnv
    dockerfile-mode
    dumb-jump
    eat
    emmet-mode
    ess
    evil
    evil-collection
    exec-path-from-shell
    f
    feature-mode
    fic-mode
    flymake-clippy
    fsharp-mode
    git-link
    go-mode
    groovy-mode
    haskell-mode
    helpful
    highlight-escape-sequences
    highlight-indent-guides
    highlight-quoted
    hydra
    idris-mode
    inf-ruby
    ivy
    json5-ts-mode
    julia-mode
    just-mode
    kotlin-mode
    magit
    markdown-mode
    merlin
    native-complete
    nginx-mode
    nix-mode
    nodejs-repl
    org
    org-cliplink
    orgit
    outline-indent
    ox-gfm
    ox-jira
    ox-reveal
    pandoc-mode
    persp-projectile
    perspective
    pest-mode
    poly-markdown
    polymode
    pov-mode
    powershell
    prettier
    projectile
    protobuf-mode
    purescript-mode
    python
    py-isort
    pyvenv
    racket-mode
    rainbow-delimiters
    rainbow-mode
    rbs-mode
    real-auto-save
    rg
    rspec-mode
    rubocop
    ruby-test-mode
    rust-mode
    s
    sed-mode
    smartparens
    swift-mode
    systemd
    telephone-line
    terraform-mode
    toml-mode
    treesit-grammars.with-all-grammars
    tuareg
    typescript-mode
    undo-fu
    unfill
    w3m
    web-mode
    window-number
    yaml-mode
  ]
  ))
